<h2>Edit New Contact</h2>
<?php echo $this->getContent() ?>

<?php echo $this->tag->form("contacts/update") ?>

	<p>
		<?php echo $this->tag->hiddenField("id") ?>
	</p>

	<p>
		<label for="img">Selecione uma imagem</label>
		<?php echo $this->tag->fileField(["img", "directory", "id" => "img"]) ?>
	</p>

	<p>
		<label for="name">Nome</label>
		<?php echo $this->tag->textField("name") ?>
	</p>

	<p>
		<label for="phone">Telefone</label>
		<?php echo $this->tag->textField("phone")?>
	</p>

	<p>
		<label for="email">E-Mail</label>
		<?php echo $this->tag->textField("email")?>
	</p>

	<p>
		<label for="age">Idade</label>
		<?php echo $this->tag->textField("age")?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Atualizar") ?>
	</p>

</form>

</br>
<?php echo $this->tag->linkTo('contacts/index/', '← Voltar') ?>