<h2><?php echo $title; ?></h2>
<?php echo $this->getContent() ?>

<table class="table">
	<tr>
		<th>Avatar</th>
		<th>Nome</th>
		<th>Email</th>
		<th>Telefone</th>
		<th>Idade</th>
		<!--<th>Cidade</th>-->
	</tr>

	<?php foreach ($contacts as $contact) { ?>
		<tr>
			<td><img src='/img/<?php echo $contact->img ?>' height="42" width="42"></td>
			<td><?php echo $contact->name ?></td>
			<td><?php echo $contact->email ?></td>
			<td><?php echo $contact->phone ?></td>
			<td><?php echo $contact->age ?></td>
			<td><?php echo $this->tag->linkTo('contacts/edit/'.$contact->id, 'Editar') ?></td>
			<td><?php echo $this->tag->linkTo('contacts/delete/'.$contact->id, 'Deletar') ?></td>
		</tr>
	<?php } ?>
</table>

</br>
<?php echo $this->tag->linkTo('contacts/new/', 'Adicionar Novo Contato') ?>
