<h2><?php echo $title; ?></h2>
<?php echo $this->getContent() ?>

<table class="table">
	<tr>
		<th>Nome</th>
		<th>UF</th>
	</tr>

	<?php foreach ($citys as $city) { ?>
		<tr>
			<td><?php echo $city->name ?></td>
			<td><?php echo $city->uf ?></td>
			<td><?php echo $this->tag->linkTo('citys/edit/'.$city->id, 'Editar') ?></td>
			<td><?php echo $this->tag->linkTo('citys/delete/'.$city->id, 'Deletar') ?></td>
		</tr>
	<?php } ?>
</table>

</br>
<?php echo $this->tag->linkTo('citys/new/', 'Adicionar Novo Contato') ?>
